<?php
/**
 * Detail repository.
 */
namespace AppBundle\Repository;

use AppBundle\Entity\Detail;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * DetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param Detail $detail Detail entity
     */
    public function save(Detail $detail)
    {
        $this->_em->persist($detail);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Detail $detail Detail entity
     */
    public function delete(Detail $detail)
    {
        $this->_em->remove($detail);
        $this->_em->flush();
    }

    /**
     * Gets detail by fos user.
     *
     * @param integer $id
     *
     * @return \Doctrine\ORM\Query
     */
    public function findDetail($id)
    {
        $qb = $this->createQueryBuilder('detail')
            ->select('detail')
            ->where('fos_userId.id = :id')
            ->setParameter(':id', $id);
       //$paginator = new Pagerfanta(new DoctrineORMAdapter($qb, false));
     //   $paginator->setMaxPerPage(Detail::NUM_ITEMS);
      //  $paginator->setCurrentPage($page);

        return $qb;
    }

    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Detail::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll()
    {
        return $this->createQueryBuilder('detail');
    }
}
