<?php
/**
 * Director repository.
 */
namespace AppBundle\Repository;

use AppBundle\Entity\Director;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * DirectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectorRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param Director $director Director entity
     */
    public function save(Director $director)
    {
        $this->_em->persist($director);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Director $director Director entity
     */
    public function delete(Director $director)
    {
        $this->_em->remove($director);
        $this->_em->flush();
    }

    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Director::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }
    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll()
    {
        $qb = $this->createQueryBuilder('d');
        $qb->select('d')
            ->orderBy('d.surname', 'ASC');

        return $qb;
    }
}
