<?php
/**
 * Location repository
 */
namespace AppBundle\Repository;

use AppBundle\Entity\Location;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param Location $location Location entity
     */
    public function save(Location $location)
    {
        $this->_em->persist($location);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Location $location Location entity
     */
    public function delete(Location $location)
    {
        $this->_em->remove($location);
        $this->_em->flush();
    }

    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Location::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }
    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll()
    {
        return $this->createQueryBuilder('id');
    }
}
