<?php
/**
 * Payment method repository.
 */

namespace AppBundle\Repository;

use AppBundle\Entity\PaymentMethod;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * PaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param PaymentMethod $paymentmethod PaymentMethod entity
     */
    public function save(PaymentMethod $paymentmethod)
    {
        $this->_em->persist($paymentmethod);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param PaymentMethod $paymentmethod PaymentMethod entity
     */
    public function delete(PaymentMethod $paymentmethod)
    {
        $this->_em->remove($paymentmethod);
        $this->_em->flush();
    }

    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(PaymentMethod::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }
    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll()
    {
        return $this->createQueryBuilder('paymentmethod');
    }
}
