<?php
/**
 * Transaction repository.
 */
namespace AppBundle\Repository;

use AppBundle\Entity\Transaction;
use UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param Transaction $transaction Transaction entity
     */
    public function save(Transaction $transaction)
    {
        $this->_em->persist($transaction);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Transaction $transaction Transaction entity
     */
    public function delete(Transaction $transaction)
    {
        $this->_em->remove($transaction);
        $this->_em->flush();
    }

    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Transaction::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }
    /**
     * Gets transactions by user.
     *
     * @param integer $user User
     * @param integer $page Page number
     *
     * @return \Doctrine\ORM\Query
     */
    public function findByUserPaginated($user, $page = 1)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->select('t')
            ->where('t.user= :user')
            ->setParameter(':user', $user)
            ->orderBy('t.date', 'ASC');
        $paginator = new Pagerfanta(new DoctrineORMAdapter($qb, false));
        $paginator->setMaxPerPage(User::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll()
    {
        return $this->createQueryBuilder('id');
    }
}
