# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.repository.play:
            class: Doctrine\ORM\EntityRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
                - AppBundle\Entity\Play

    app.repository.director:
                class: Doctrine\ORM\EntityRepository
                factory: ['@doctrine.orm.default_entity_manager', getRepository]
                arguments:
                    - AppBundle\Entity\Director

    app.repository.location:
                    class: Doctrine\ORM\EntityRepository
                    factory: ['@doctrine.orm.default_entity_manager', getRepository]
                    arguments:
                        - AppBundle\Entity\Location

    app.repository.spectacle:
                    class: Doctrine\ORM\EntityRepository
                    factory: ['@doctrine.orm.default_entity_manager', getRepository]
                    arguments:
                        - AppBundle\Entity\Spectacle

    app.repository.transaction:
                    class: Doctrine\ORM\EntityRepository
                    factory: ['@doctrine.orm.default_entity_manager', getRepository]
                    arguments:
                        - AppBundle\Entity\Transaction
                        
    app.repository.detail:
                    class: Doctrine\ORM\EntityRepository
                    factory: ['@doctrine.orm.default_entity_manager', getRepository]
                    arguments:
                        - AppBundle\Entity\Detail
    app.repository.status:
                    class: Doctrine\ORM\EntityRepository
                    factory: ['@doctrine.orm.default_entity_manager', getRepository]
                    arguments:
                        - AppBundle\Entity\Status
                        
                        
    app.repository.address:
                    class: Doctrine\ORM\EntityRepository
                    factory: ['@doctrine.orm.default_entity_manager', getRepository]
                    arguments:
                        - AppBundle\Entity\Address
    app.twig_extension:
            class: AppBundle\Twig\AppExtension
            public: false
            tags:
                - { name: twig.extension }

    app.form.handler.registration:
        class: AppBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false
        
